Make image and url absolute path for meta tags
2RockSoftware/marble pull request #15
Opened 2022-04-14 17:55 UTC by DelGall

2022-04-15 14:46 UTC, PeterGrand requested changes
It would be ideal to populate these tags dynamically instead of hard coding the urls. So I've added suggestions for that.

2022-04-15 14:46 UTC, PeterGrand commented on marble/templates/base.html
> +    <meta property="twitter:url" content="https://tworock.io/">
```suggestion
    <meta property="twitter:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}">
```

2022-04-15 14:46 UTC, PeterGrand commented on marble/templates/base.html
> +    <meta property="og:url" content="https://tworock.io/">
```suggestion
    <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}">
```

2022-04-15 14:46 UTC, PeterGrand commented on marble/templates/base.html
> +    <meta name="twitter:image" content="https://tworock.io/static/images/two-rock-software-social.jpg">
```suggestion
    <meta name="twitter:image" content="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}{% static 'images/two-rock-software-social.jpg' %}">
```

2022-04-15 14:46 UTC, PeterGrand commented on marble/templates/base.html
> +    <meta property="og:image" content="https://tworock.io/static/images/two-rock-software-social.jpg">
```suggestion
    <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}{% static 'images/two-rock-software-social.jpg' %}">
```

2022-04-19 17:33 UTC, DelGall reviewed
Updated meta tags.

2022-04-20 12:59 UTC, merged